/* Generated By:JavaCC: Do not edit this line. BOBJConstants.java */
package bobj;

public interface BOBJConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 10;
  int OBJ = 12;
  int TH = 13;
  int BTH = 14;
  int DTH = 15;
  int ENDO = 16;
  int ENDTH = 17;
  int ENDB = 18;
  int ENDD = 19;
  int END = 20;
  int PR = 21;
  int PROTECTING = 22;
  int EX = 23;
  int EXTENDING = 24;
  int US = 25;
  int USE = 26;
  int USING = 27;
  int INC = 28;
  int INCLUDING = 29;
  int IS = 30;
  int SORT = 31;
  int SORTS = 32;
  int BSORT = 33;
  int BSORTS = 34;
  int PSORT = 35;
  int SUBSORT = 36;
  int SUBSORTS = 37;
  int VAR = 38;
  int VARS = 39;
  int OP = 40;
  int OPS = 41;
  int OPAS = 42;
  int EQ = 43;
  int CQ = 44;
  int CEQ = 45;
  int ASSOC = 46;
  int COMM = 47;
  int IDEM = 48;
  int PREC = 49;
  int IDR = 50;
  int ID = 51;
  int NONCONG = 52;
  int MEMO = 53;
  int LESS = 54;
  int ARROW = 55;
  int DOT = 56;
  int VARSOF = 57;
  int COLON = 58;
  int DOUBLECOLON = 59;
  int ADD = 60;
  int SUM = 61;
  int TO = 62;
  int STAR = 63;
  int LB = 64;
  int RB = 65;
  int DFN = 66;
  int RED = 67;
  int BRED = 68;
  int SOLVE = 69;
  int OPEN = 70;
  int OPENR = 71;
  int CLOSE = 72;
  int VIEW = 73;
  int ENDV = 74;
  int FROM = 75;
  int LOAD = 76;
  int APPLY = 77;
  int START = 78;
  int AT = 79;
  int WITH = 80;
  int WITHIN = 81;
  int PRINT = 82;
  int PARENS = 83;
  int OF = 84;
  int QUIT = 85;
  int PWD = 86;
  int CD = 87;
  int LS = 88;
  int IN = 89;
  int SHOW = 90;
  int MAKE = 91;
  int ENDM = 92;
  int LET = 93;
  int COMMENT = 94;
  int COBASIS = 95;
  int COB = 96;
  int COV = 97;
  int STOP = 98;
  int SELECT = 99;
  int SET = 100;
  int TRACE = 101;
  int ON = 102;
  int OFF = 103;
  int FULL = 104;
  int PARSE = 105;
  int INCLUDE = 106;
  int REDUCTION = 107;
  int REDUCE = 108;
  int TIME = 109;
  int RULES = 110;
  int JBO = 111;
  int ASSOCIATIVE = 112;
  int COMMUTATIVE = 113;
  int HT = 114;
  int WEIV = 115;
  int ENDVIEW = 116;
  int GATHERING = 117;
  int PRECEDENCE = 118;
  int THEORY = 119;
  int SH = 120;
  int LONGQUIT = 121;
  int IDEMPOTENT = 122;
  int OBJECT = 123;
  int IDENTITY = 124;
  int DEFINE = 125;
  int INPUT = 126;
  int CONTEXT = 127;
  int CASE = 128;
  int FOR = 129;
  int MORPH = 130;
  int MB = 131;
  int INTEGER_LITERAL = 132;
  int DECIMAL_LITERAL = 133;
  int HEX_LITERAL = 134;
  int OCTAL_LITERAL = 135;
  int FLOATING_POINT_LITERAL = 136;
  int EXPONENT = 137;
  int CHARACTER_LITERAL = 138;
  int STRING_LITERAL = 139;
  int IDENTIFIER = 140;
  int SYMBOL = 141;
  int LETTER = 142;
  int DIGIT = 143;

  int DEFAULT = 0;
  int MULTIPLE_LINE_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"***(\"",
    "\")***\"",
    "<token of kind 8>",
    "\"***\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 11>",
    "\"obj\"",
    "\"th\"",
    "\"bth\"",
    "\"dth\"",
    "\"endo\"",
    "\"endth\"",
    "\"endb\"",
    "\"endd\"",
    "\"end\"",
    "\"pr\"",
    "\"protecting\"",
    "\"ex\"",
    "\"extending\"",
    "\"us\"",
    "\"use\"",
    "\"using\"",
    "\"inc\"",
    "\"including\"",
    "\"is\"",
    "\"sort\"",
    "\"sorts\"",
    "\"dsort\"",
    "\"dsorts\"",
    "\"psort\"",
    "\"subsort\"",
    "\"subsorts\"",
    "\"var\"",
    "\"vars\"",
    "\"op\"",
    "\"ops\"",
    "\"op-as\"",
    "\"eq\"",
    "\"cq\"",
    "\"ceq\"",
    "\"assoc\"",
    "\"comm\"",
    "\"idem\"",
    "\"prec\"",
    "\"idr:\"",
    "\"id:\"",
    "\"ncong\"",
    "\"memo\"",
    "\"<\"",
    "\"->\"",
    "\".\"",
    "\"vars-of\"",
    "\":\"",
    "\"::\"",
    "\"+\"",
    "\"||\"",
    "\"to\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
    "\"dfn\"",
    "\"red\"",
    "\"cred\"",
    "\"solve\"",
    "\"open\"",
    "\"openr\"",
    "\"close\"",
    "\"view\"",
    "\"endv\"",
    "\"from\"",
    "\"load\"",
    "\"apply\"",
    "\"start\"",
    "\"at\"",
    "\"with\"",
    "\"within\"",
    "\"print\"",
    "\"parens\"",
    "\"of\"",
    "\"q\"",
    "\"pwd\"",
    "\"cd\"",
    "\"ls\"",
    "\"in\"",
    "\"show\"",
    "\"make\"",
    "\"endm\"",
    "\"let\"",
    "\"***>\"",
    "\"cobasis\"",
    "\"cob\"",
    "\"cov\"",
    "\"eof\"",
    "\"select\"",
    "\"set\"",
    "\"trace\"",
    "\"on\"",
    "\"off\"",
    "\"full\"",
    "\"parse\"",
    "\"include\"",
    "\"reduction\"",
    "\"reduce\"",
    "\"time\"",
    "\"rules\"",
    "\"jbo\"",
    "\"associative\"",
    "\"commutative\"",
    "\"ht\"",
    "\"weiv\"",
    "\"endview\"",
    "\"gathering\"",
    "\"precedence\"",
    "\"theory\"",
    "\"sh\"",
    "\"quit\"",
    "\"idempotent\"",
    "\"object\"",
    "\"identity\"",
    "\"define\"",
    "\"input\"",
    "\"context\"",
    "\"case\"",
    "\"for\"",
    "\"morph\"",
    "\"mb\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<SYMBOL>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
